/*
 *      Copyright 2018 Pavel Bludov <pbludov@gmail.com>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License along
 *      with this program; if not, write to the Free Software Foundation, Inc.,
 *      51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "usbcommandedit.h"

#ifndef _countof
#define _countof(x) (sizeof(x)/sizeof(*x))
#endif

// http://www.usb.org/developers/hidpage/Hut1_12v2.pdf (15 Consumer Page 0x0C)
// https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hid/hid-input.c (lines 766-930)

enum KeyGroup
{
    RESERVED,
    CONTROL,
    MENU,
    DISPLAY,
    SELECTION,
    TRANSPORT,
    SEARCH,
    AUDIO,
    SPEED,
    LAUNCH,
    GUI,
};

static struct EnumEdit::Item UsbCmdItems[] =
{
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Power", CONTROL},
    {"Reset", CONTROL},
    {"Sleep", CONTROL},
    {"Sleep After", CONTROL},
    {"Sleep Mode", CONTROL},
    {"Keyboard Illumination", CONTROL},
    {"Generic Button", CONTROL},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Menu", MENU},
    {"Menu Pick", MENU},
    {"Menu Up", MENU},
    {"Menu Down", MENU},
    {"Menu Left", MENU},
    {"Menu Right", MENU},
    {"Menu Escape", MENU},
    {"Menu Value Increase", MENU},
    {"Menu Value Decrease", MENU},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Data On Screen", DISPLAY},    // 0x60
    {"Closed Caption", DISPLAY},
    {"Closed Caption Select", DISPLAY},
    {"VCR/TV", DISPLAY},
    {"Broadcast Mode", DISPLAY},
    {"Snapshot", DISPLAY},
    {"Still", DISPLAY},
    {"", RESERVED},
    {"", RESERVED},
    {"Red", DISPLAY},
    {"Green", DISPLAY},
    {"Blue", DISPLAY},
    {"Yellow", DISPLAY},
    {"Zoom", DISPLAY},
    {"", RESERVED},
    {"Brightness Up", DISPLAY},

    {"Brightness Down", DISPLAY},
    {"Brightness Toggle", DISPLAY},
    {"Brightness Min", DISPLAY},
    {"Brightness Max", DISPLAY},
    {"Brightness Auto", DISPLAY},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"Assign Selection", SELECTION},
    {"Mode Step", SELECTION},
    {"Recall Last", SELECTION},
    {"Enter Channel", SELECTION},
    {"Order Movie", SELECTION},
    {"Channel", SELECTION},
    {"Media Selection", SELECTION},
    {"Media Select Computer", SELECTION},
    {"Media Select TV", SELECTION},
    {"Media Select WWW", SELECTION},
    {"Media Select DVD", SELECTION},
    {"Media Select Telephone", SELECTION},
    {"Media Select Program Guide", SELECTION},
    {"Media Select Video Phone", SELECTION},
    {"Media Select Games", SELECTION},

    {"Media Select Messages", SELECTION},
    {"Media Select CD", SELECTION},
    {"Media Select VCR", SELECTION},
    {"Media Select Tuner", SELECTION},
    {"Quit", SELECTION},
    {"Help", SELECTION},
    {"Media Select Tape", SELECTION},
    {"Media Select Cable", SELECTION},
    {"Media Select Satellite", SELECTION},
    {"Media Select Security", SELECTION},
    {"Media Select Home", SELECTION},
    {"Media Select Call", SELECTION},
    {"Channel Increment", SELECTION},
    {"Channel Decrement", SELECTION},
    {"Media Select", SELECTION},
    {"", RESERVED},

    {"VCR Plus", SELECTION},
    {"Once", SELECTION},
    {"Daily", SELECTION},
    {"Weekly", SELECTION},
    {"Monthly", SELECTION},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Play", TRANSPORT},
    {"Pause", TRANSPORT},
    {"Record", TRANSPORT},
    {"Fast Forward", TRANSPORT},
    {"Rewind", TRANSPORT},
    {"Scan Next Track", TRANSPORT},
    {"Scan Previous Track", TRANSPORT},
    {"Stop", TRANSPORT},
    {"Eject", TRANSPORT},
    {"Random Play", TRANSPORT},
    {"Select Disc", TRANSPORT},
    {"Enter Disc", TRANSPORT},
    {"Repeat", TRANSPORT},
    {"Tracking", TRANSPORT},
    {"Track Normal", TRANSPORT},
    {"Slow Tracking", TRANSPORT},

    {"Frame Forward", TRANSPORT},
    {"Frame Back", TRANSPORT},

    {"Mark", SEARCH},
    {"Clear Mark", SEARCH},
    {"Repeat From Mark", SEARCH},
    {"Return To Mark", SEARCH},
    {"Search Mark Forward", SEARCH},
    {"Search Mark Backwards", SEARCH},
    {"Counter Reset", SEARCH},
    {"Show Counter", SEARCH},
    {"Tracking Increment", TRANSPORT},
    {"Tracking Decrement", TRANSPORT},
    {"Stop/Eject", TRANSPORT},
    {"Play/Pause", TRANSPORT},
    {"Play/Skip", TRANSPORT},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Volume", AUDIO},
    {"Balance", AUDIO},
    {"Mute", AUDIO},
    {"Bass", AUDIO},
    {"Treble", AUDIO},
    {"Bass Boost", AUDIO},
    {"Surround Mode", AUDIO},
    {"Loudness", AUDIO},
    {"MPX", AUDIO},
    {"Volume Increment", AUDIO},
    {"Volume Decrement", AUDIO},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"Speed Select", SPEED},
    {"Playback Speed", SPEED},
    {"Standard Play", SPEED},
    {"Long Play", SPEED},
    {"Extended Play", SPEED},
    {"Slow", SPEED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"Launch Button Configuration Tool", LAUNCH},
    {"Programmable Button Configuration", LAUNCH},
    {"Consumer Control Configuration", LAUNCH},
    {"Word Processor", LAUNCH},
    {"Text Editor", LAUNCH},
    {"Spreadsheet", LAUNCH},
    {"Graphics Editor", LAUNCH},
    {"Presentation App", LAUNCH},
    {"Database App", LAUNCH},
    {"Email Reader", LAUNCH},
    {"Newsreader", LAUNCH},
    {"Voicemail", LAUNCH},
    {"Contacts/Address Book", LAUNCH},
    {"Calendar/Schedule", LAUNCH},
    {"Task/Project Manager", LAUNCH},

    {"Log/Journal/Timecard", LAUNCH},
    {"Checkbook/Finance", LAUNCH},
    {"Calculator", LAUNCH},
    {"A/V Capture/Playback", LAUNCH},
    {"Local Machine Browser", LAUNCH},
    {"LAN/WAN Browser", LAUNCH},
    {"Internet Browser", LAUNCH},
    {"Remote Networking/ISP Connect", LAUNCH},
    {"Network Conference", LAUNCH},
    {"Network Chat", LAUNCH},
    {"Telephony/Dialer", LAUNCH},
    {"Logon", LAUNCH},
    {"Logoff", LAUNCH},
    {"Logon/Logoff", LAUNCH},
    {"Terminal Lock/Screensaver", LAUNCH},
    {"Control Panel", LAUNCH},

    {"Command Line Processor/Run", LAUNCH},
    {"Process/Task Manager", LAUNCH},
    {"Select Task/Application", LAUNCH},
    {"Next Task/Application", LAUNCH},
    {"Previous Task/Application", LAUNCH},
    {"Preemptive Halt Task/Application", LAUNCH},
    {"Integrated Help Center", LAUNCH},
    {"Documents", LAUNCH},
    {"Thesaurus", LAUNCH},
    {"Dictionary", LAUNCH},
    {"Desktop", LAUNCH},
    {"Spell Check", LAUNCH},
    {"Grammar Check", LAUNCH},
    {"Wireless Status", LAUNCH},
    {"Keyboard Layout", LAUNCH},
    {"Virus Protection", LAUNCH},

    {"Encryption", LAUNCH},
    {"Screen Saver", LAUNCH},
    {"Alarms", LAUNCH},
    {"Clock", LAUNCH},
    {"File Browser", LAUNCH},
    {"Power Status", LAUNCH},
    {"Image Browser", LAUNCH},
    {"Audio Browser", LAUNCH},
    {"Movie Browser", LAUNCH},
    {"Digital Rights Manager", LAUNCH},
    {"Digital Wallet", LAUNCH},
    {"", RESERVED},
    {"Instant Messaging", LAUNCH},
    {"OEM Features/ Tips/Tutorial Browser", LAUNCH},
    {"OEM Help", LAUNCH},
    {"Online Community", LAUNCH},

    {"Entertainment Content Browser", LAUNCH},
    {"Online Shopping Browser", LAUNCH},
    {"SmartCard Information/Help", LAUNCH},
    {"Market Monitor/Finance Browser", LAUNCH},
    {"Customized Corporate News Browser", LAUNCH},
    {"Online Activity Browser", LAUNCH},
    {"Research/Search Browser", LAUNCH},
    {"Audio Player", LAUNCH},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"New", GUI},
    {"Open", GUI},
    {"Close", GUI},
    {"Exit", GUI},
    {"Maximize", GUI},
    {"Minimize", GUI},
    {"Save", GUI},
    {"Print", GUI},
    {"Properties", GUI},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},

    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"", RESERVED},
    {"Undo", GUI},
    {"Copy", GUI},
    {"Cut", GUI},
    {"Paste", GUI},
    {"Select All", GUI},
    {"Find", GUI},

    {"Find and Replace", GUI},
    {"Search", GUI},
    {"Go To", GUI},
    {"Home", GUI},
    {"Back", GUI},
    {"Forward", GUI},
    {"Stop", GUI},
    {"Refresh", GUI},
    {"Previous Link", GUI},
    {"Next Link", GUI},
    {"Bookmarks", GUI},
    {"History", GUI},
    {"Subscriptions", GUI},
    {"Zoom In", GUI},
    {"Zoom Out", GUI},
    {"Zoom LC 15.16	", GUI},

    {"Full Screen View", GUI},
    {"Normal View", GUI},
    {"View Toggle", GUI},
    {"Scroll Up", GUI},
    {"Scroll Down", GUI},
    {"Scroll LC 15.16	", GUI},
    {"Pan Left", GUI},
    {"Pan Right", GUI},
    {"Pan LC 15.16	", GUI},
    {"New Window", GUI},
    {"Tile Horizontally", GUI},
    {"Tile Vertically", GUI},
    {"Format", GUI},
    {"Edit Sel 15.14	", GUI},
    {"Bold", GUI},
    {"Italics", GUI},

    {"Underline", GUI},
    {"Strikethrough", GUI},
    {"Subscript", GUI},
    {"Superscript", GUI},
    {"All Caps", GUI},
    {"Rotate", GUI},
    {"Resize", GUI},
    {"Flip horizontal", GUI},
    {"Flip Vertical", GUI},
    {"Mirror Horizontal", GUI},
    {"Mirror Vertical", GUI},
    {"Font Select", GUI},
    {"Font Color", GUI},
    {"Font Size", GUI},
    {"Justify Left", GUI},
    {"Justify Center H", GUI},

    {"Justify Right", GUI},
    {"Justify Block H", GUI},
    {"Justify Top", GUI},
    {"Justify Center V", GUI},
    {"Justify Bottom", GUI},
    {"Justify Block V", GUI},
    {"Indent Decrease", GUI},
    {"Indent Increase", GUI},
    {"Numbered List", GUI},
    {"Restart Numbering", GUI},
    {"Bulleted List", GUI},
    {"Promote", GUI},
    {"Demote", GUI},
    {"Yes", GUI},
    {"No", GUI},
    {"Cancel", GUI},

    {"Catalog", GUI},
    {"Buy/Checkout", GUI},
    {"Add to Cart", GUI},
    {"Expand", GUI},
    {"Expand All", GUI},
    {"Collapse", GUI},
    {"Collapse All", GUI},
    {"Print Preview", GUI},
    {"Paste Special", GUI},
    {"Insert Mode", GUI},
    {"Delete", GUI},
    {"Lock", GUI},
    {"Unlock", GUI},
    {"Protect", GUI},
    {"Unprotect", GUI},
    {"Attach Comment", GUI},

    {"Delete Comment", GUI},
    {"View Comment", GUI},
    {"Select Word", GUI},
    {"Select Sentence", GUI},
    {"Select Paragraph", GUI},
    {"Select Column", GUI},
    {"Select Row", GUI},
    {"Select Table", GUI},
    {"Select Object", GUI},
    {"Redo/Repeat", GUI},
    {"Sort", GUI},
    {"Sort Ascending", GUI},
    {"Sort Descending", GUI},
    {"Filter", GUI},
    {"Set Clock", GUI},
    {"View Clock", GUI},

    {"Select Time Zone", GUI},
    {"Edit Time Zones", GUI},
    {"Set Alarm", GUI},
    {"Clear Alarm", GUI},
    {"Snooze Alarm", GUI},
    {"Reset Alarm", GUI},
    {"Synchronize", GUI},
    {"Send/Receive", GUI},
    {"Send To", GUI},
    {"Reply", GUI},
    {"Reply All", GUI},
    {"Forward Msg", GUI},
    {"Send", GUI},
    {"Attach File", GUI},
    {"Upload", GUI},
    {"Download (Save Target As)", GUI},

    {"Set Borders", GUI},
    {"Insert Row", GUI},
    {"Insert Column", GUI},
    {"Insert File", GUI},
    {"Insert Picture", GUI},
    {"Insert Object", GUI},
    {"Insert Symbol", GUI},
    {"Save and Close", GUI},
    {"Rename", GUI},
    {"Merge", GUI},
    {"Split", GUI},
    {"Disribute Horizontally", GUI},
    {"Distribute Vertically	", GUI},

},
UsbCmdGroups[] =
{
    {QT_TR_NOOP("Control"),   CONTROL},
    {QT_TR_NOOP("Menu"),      MENU},
    {QT_TR_NOOP("Display"),   DISPLAY},
    {QT_TR_NOOP("Selection"), SELECTION},
    {QT_TR_NOOP("Media"),     TRANSPORT},
    {QT_TR_NOOP("Search"),    SEARCH},
    {QT_TR_NOOP("Audio"),     AUDIO},
    {QT_TR_NOOP("Speed"),     SPEED},
    {QT_TR_NOOP("Launch"),    LAUNCH},
    {QT_TR_NOOP("Gui"),       GUI},
};

static std::vector<EnumEdit::Item> usbCmdItems(UsbCmdItems, UsbCmdItems + _countof(UsbCmdItems));
static std::vector<EnumEdit::Item> usbCmdGroups(UsbCmdGroups, UsbCmdGroups + _countof(UsbCmdGroups));

UsbCommandEdit::UsbCommandEdit(QWidget *parent)
    : EnumEdit(usbCmdItems, usbCmdGroups, parent)
{
}

